config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'welcome/index'
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.new_contact_submission(@contact).deliver_now
      ContactMailer.thanks(@contact).deliver_now
      redirect_to contacts_url
    else
      flash[:alert] = "Contact not saved"
      render :new
    end
  end

  def index
    @contacts = Contact.all
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<% @contacts.each do |contact| %>
  <div>
    <i><%= contact.id %></i>
    <br />
    <b><%= contact.name %></b><br />
    <%= contact.email %><br />
    <%= contact.message %>
  </div>
<% end %>

<p><%= link_to "New Contact", new_contact_path %></p>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </p>

  <p>
  <%= f.label :message %>
  <%= f.text_area :message %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div>Mary &amp; Ferrari</div>
      <h2><%= link_to "Practice", root_url %></h2>
    </header>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<p>
This is a sandbox application to test out new functionalities before adding them to a
client's site.
</p>

<p>
It's hosted on Heroku at: 
<%= link_to "mf-practice.herokuapp.com", "https://mf-practice.herokuapp.com/" %>
</p>

<h2>Contact form</h2>
<p>It creates a new Contact resource and sends an email to the site admin.</p>
<p><%= link_to "Contacts", contacts_path %></p>


<div class="flex justify-center bg-gray-300">
<div class="mx-4 my-10 self-center text-center">
  <h1>Welcome to NorthBy</h1>
  <h2 class="text-3xl font-semibold text-blue-300">A premium in sight and sound</h2>
  <button class="my-4 px-4 py-2 border-2 border-black rounded-lg text-white bg-blue-900">Learn more</button>
</div>
</div>


  <%= image_tag 'g-logo.png', class: "transform transition duration-1000 hover:box-shadow-lg" %>

  <div class="w-40 h-40 bg-gray-300 transform transition duration-1000 hover:box-shadow-lg">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
</svg>
  </div>